"use client";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SessionProvider } from 'next-auth/react';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

<<<<<<< HEAD
=======
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

>>>>>>> 43af0cdb86ebed7b53c65975454e486665e8198e
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>MultiAgent Code Debugger</title>
        <meta name="description" content="AI-powered code debugging platform" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<<<<<<< HEAD
        <SessionProvider>
          {children}
        </SessionProvider>
=======
        {children}
>>>>>>> 43af0cdb86ebed7b53c65975454e486665e8198e
      </body>
    </html>
  );
}
